=== DoDGOSS/ozp-data-schemas/schema/vnd.ozp-iwc-intent-handler-v1+json.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "A description of an intent handler.",
    "type": "object",
    "id": "http://ozoneplatform.org/jsonschema/vnd.ozp-iwc-intent-handler-v1+json.json",
    "required" : ["action","type"],
    "properties": {
        "_links": {
            "properties": {
                "describes": {
                    "allOf": [
                        {
                            "type": "object",
                            "description": "The URL to open a new instance of the intent handler."
                        },
                        {"$ref" : "hal-schema.json#/properties/_links"}
                    ]
                }
            },
            "additionalProperties":  { "$ref" : "hal-schema.json#/properties/_links"}
        },
        "_embedded": {
            "type": "object",
            "properties": {},
            "additionalProperties": { "$ref": "hal-schema.json#/properties/_embedded" }
        },
        "type": {
            "type" : "string",
            "format": "mimeType",
            "description": "The content type for this intent."
        },
        "action" : {
            "type": "string",
            "description": "The action that this intent takes."
        },
        "icon" : {
            "type": "string",
            "format": "uri",
            "description": "An image that can be used to represent this intent."
        },
        "label" : {
            "type": "string",
            "description": "A label suitable for use as a menu option or short tooltip."
        },
        "invokeIntent" : {
            "allOf": [
                {
                    "type": "object",
                    "description": "A packet fragment to be sent when this intent is invoked."
                },
                {"$ref": "vnd.ozp-iwc-transport-packet+json.json"}
            ]
        }
    },
    "allOf": [{ "$ref": "ozp-schema-parts.json#definitions/iwc" }]
}

=== DoDGOSS/ozp-data-schemas/mock/api/profile/v1/exampleUser/intent/text/plain/edit/index.json
{
    "_links": {
        "self" : {"href": "/api/profile/v1/exampleUser/intent/text/plain/edit"},
        "ozp:iwcSelf" : {"href" : "intents.api/text/plain/edit"}
    },
    "type": "text/plain",
    "action": "edit",
    "icon": "http://example.com/edit-text-plain.png",
    "label": "Edit plain text"
}

=== DoDGOSS/ozp-data-schemas/mock/api/profile/v1/exampleUser/intent/application/ozp-demo-ball+json/view/index.json
{
    "_links": {
        "self" : {"href" : "/api/profile/v1/exampleUser/intent/application/ozp-demo-ball+json/view"},
        "ozp:iwcSelf" : {"href" : "intents.api/application/ozp-demo-ball+json/view"}
    },
    "type": "application/ozp-demo-ball+json",
    "action": "view",
    "icon": "http://example.com/view-text-plain.png",
    "label": "View a bouncing ball"
}
